# Generated by Django 4.1 on 2022-11-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="upload/images")),
                ("book_name", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
                ("original_price", models.IntegerField(default=0)),
                ("description", models.TextField()),
            ],
        ),
    ]
