# Generated by Django 4.1 on 2022-11-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0003_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="upload/images")),
                ("description", models.TextField()),
                ("name", models.CharField(max_length=100)),
                ("skills", models.CharField(max_length=100)),
            ],
        ),
    ]
