# Generated by Django 4.1 on 2022-11-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0004_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone_no", models.IntegerField(default=0)),
                ("message", models.TextField()),
            ],
        ),
    ]
