# Generated by Django 4.1 on 2022-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0005_contactus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plain", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
                ("time", models.CharField(max_length=100)),
                ("space", models.IntegerField(default=0)),
                ("transfer", models.IntegerField(default=0)),
                ("pannel", models.CharField(max_length=100)),
                ("support", models.IntegerField(default=0)),
                ("email", models.CharField(max_length=100)),
                ("security", models.CharField(max_length=10)),
            ],
        ),
    ]
